nodes:
  - node: 1
    publicIpAddress: "192.168.0.3"
    publicPort: "554"
    latitude:
    longitude:
  - node: 2
    publicIpAddress: "192.168.0.44"
    publicPort: "554"
    latitude:
    longitude: