services:
  vrc-haven:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080/tcp" # API
      - "8890:8890/udp" # SRT Port (only needed for the Flagship)
      - "554:554/udp" # RTSP Port
    deploy:
      resources:
        limits:
          cpus: "6.0"
          memory: 8192M
