// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// EscortAnnounce defines model for EscortAnnounce.
type EscortAnnounce struct {
	// EscortId The ID of the escort.
	EscortId string `json:"escort_id"`
}

// EscortDescribe defines model for EscortDescribe.
type EscortDescribe struct {
	// EscortId The ID of the escort.
	EscortId string `json:"escort_id"`

	// Latitude The latitude of the escort's location.
	Latitude float32 `json:"latitude"`

	// Longitude The longitude of the escort's location.
	Longitude float32 `json:"longitude"`

	// RtspPort The RTSP port of the escort.
	RtspPort int `json:"rtsp_port"`
}

// PostEscortAnnounceJSONRequestBody defines body for PostEscortAnnounce for application/json ContentType.
type PostEscortAnnounceJSONRequestBody = EscortAnnounce

// PostEscortDescribeJSONRequestBody defines body for PostEscortDescribe for application/json ContentType.
type PostEscortDescribeJSONRequestBody = EscortDescribe

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Announces a escort to the Haven.
	// (POST /escort/announce)
	PostEscortAnnounce(w http.ResponseWriter, r *http.Request)
	// Describes a escort to the Haven.
	// (POST /escort/describe)
	PostEscortDescribe(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Announces a escort to the Haven.
// (POST /escort/announce)
func (_ Unimplemented) PostEscortAnnounce(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Describes a escort to the Haven.
// (POST /escort/describe)
func (_ Unimplemented) PostEscortDescribe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostEscortAnnounce operation middleware
func (siw *ServerInterfaceWrapper) PostEscortAnnounce(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEscortAnnounce(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostEscortDescribe operation middleware
func (siw *ServerInterfaceWrapper) PostEscortDescribe(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEscortDescribe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/escort/announce", wrapper.PostEscortAnnounce)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/escort/describe", wrapper.PostEscortDescribe)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RUwU4bMRD9ldG0Ulsp3SxtT3uj0KrcEFAupUKOPZsYeT2uPQtKUf69sjcLgQR6aLl5",
	"d8bvvXkz41vU3AX25CVhc4tJL6hT5fglaY6y7z33XlP+EyIHimKpxKnEL63JH4aSjjaIZY8Nni0Ijg6B",
	"W5AFwZBY4QRlGQgbTBKtn+NqNcFIv3obyWDzYwPw510qz65IC64mazmHhWf2InIm6JRY6Q3thhijD4He",
	"JHCsVc7LmC3HTgk22DpWck/i+25GsZCwnz/HMob/kSZKCpeBo+ymOTk7PYYcftIW64XmGevJNm0YtlnW",
	"Jvd2JzOc9S3vkmUT2FTU7B8fgWHdd+SlFA0txxI5p7iEE3JWeYED9kJe4O35ycE7+KauyVdw4QtShrAJ",
	"PAvkUrwhU0BCP3NWQ58IlDfA3i2hVdo6K0ooleSouet6bwfDYUZyQ+QL/1en5mlhQ7k8DGWqLnz2zYrL",
	"le5UWLRlTTjBa4ppKLmu6movd4sDeRUsNvixqqsaJxiULMpgTwfDp2pzEzmVvuYFKBKPDDZ4zEkebe3Q",
	"Okrymc0y39CDnnxUIbh1hdOrlPWM+59PryO12OCr6f0DMV2/DtNHJKuHIyKxp/IjBfZp2M4Pdb3d8NNe",
	"a0qp7Z1bwlieyXZ8qve207971cuCo/1NBt5DnmLtbDZ33WblHN+QAWEIFPOKgORJUHpYmywz9V2n4hIb",
	"HOUnUOvhzxdzi4c5Kumj+Wbz3fmL+Xdv1Euaf0fyX8wfy0uPPBpZnvFotfoTAAD//5lSO8FEBgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
