openapi: 3.0.0
info:
  title: 'VRC Haven Front Facing API'
  description: 'This API will be used for escort src to communicated with the flagship.'
  version: '0.0.1'
paths:
  '/auth/login':
    post:
      summary: 'Authenticates the user and returns a JWT token'
      description: 'Body needs to be send as a encrypted JSON string'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: 'JWT token returned on successful authentication. The content will be a encrypted JSON string.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

  '/escort/register':
    post:
      summary: 'Registers the client as a new escort'
      description: 'Body needs to be send as a encrypted JSON string'
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ipAddress:
                  type: string
                rtspEgressPort:
                  type: integer
                lat:
                  description: 'Latitude of the location of the escort'
                  type: number
                lon:
                  description: 'Longitude of the location of the escort'
                  type: number
                username:
                  type: string
                passphrase:
                  type: string
              required:
                - ipAddress
                - rtspEgressPort
                - lat
                - lon
                - username
                - passphrase
      responses:
        '200':
          description: 'Successfully registered escort'
          content:
            text/plain:
              schema:
                type: string
                example: 'Successfully registered escort'
                description: 'The string will be encrypted'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
